### ISSUE TITLE
KL430 support

### ISSUE THREAD

**Issue by alexneth** [RaresAil/homebridge-tplink-smart-light#1]
Hi, 
Does this plugin support the Kasa KL430 smart Light Strip?

The 'Tplink Smarthome' plugin for HOOBS doesn't support the light strip and work on that plugin seems to be at a crawl. Any chance this plugin will support it? 

Cheers!

**Comment by RaresAil** [comment]
Hey, sorry for the late response, I am not sure, I don't have a KL430 to test with, you can clone the project and test it, and if it not supported, maybe you can write a PR which can add support for that.

**Comment by RaresAil** [comment]
Hey @alexneth i have a RGBIC Strip from tapo L920 which works with no problems
