### ISSUE TITLE
P100 has a brightness slider in Home app

### ISSUE THREAD

**Issue by jvacek** [RaresAil/homebridge-tplink-smart-light#12]
### Describe The Bug

The socket does not have a "dimmer" function, so the brightness here is a bit misleading.

### Expected behavior

Just an on/off switch instead of a slider.

### Logs

N/A

### Plugin Config

{
    "addresses": [
        "192.168.178.208"
    ],
    "name": "TPLink Tapo",
    "email": "email",
    "password": "password",
    "platform": "HomebridgeTPLinkTapo"
}

### Plugin Version

3.0.2

### Homebridge Version

1.4.1

### Node.js Version

16.15.0

### NPM Version

8.5.5

### Operating System

Raspbian

**Comment by RaresAil** [comment]
Hello, thank you for the issue, i will investigate this and fix it

**Comment by RaresAil** [comment]
@jvacek Please update to 3.1.0 and let me know if the issue still persists

**Comment by jvacek** [comment]
I can now not have any P100 "register itself" in the instance.
```
[23/05/2022, 10:57:39] [Tapo] Adding new accessory: Mosquitto repellent
[23/05/2022, 10:57:39] [Tapo] Failed to register accessory "Mosquitto repellent" of type "Unknown"
```
Not sure if I can configure this type somewhere?

**Comment by RaresAil** [comment]
Ah P100 is a outlet not a light bulb that is why, i will work on a test version to add debug logs to can add support for outlets

**Comment by RaresAil** [comment]
I teste the changes with a P100 and is working, i will do some more tests and today i will release the fix
