### ISSUE TITLE
P100 Smart Plug no longer working

### ISSUE THREAD

**Issue by CoderHoods** [RaresAil/homebridge-tplink-smart-light#14]
### Describe The Bug

I've been using home bridge with my smart home devices on my Pi3 for a while now and it has been working beautifully
came home today and my smart home Tapo p100 plugs are no longer connecting for some reason

the ip's of the devices is still the same I checked and have tried restarting and checking everything nothing seems to work
when I deleted the devices and added them again I got the error message:
"Failed to register accessory "Desk" of type "Unknown""

Before deleting and re-adding the devices I got this message over and over:
Retry to connect in 10s : [192.168.5.213](https://192.168.5.213/)
[5/29/2022, 7:28:27 PM] [Tapo] Try for [192.168.5.213](https://192.168.5.213/) : 5/20
[5/29/2022, 7:28:27 PM] [Tapo] Session expired
[5/29/2022, 7:28:27 PM] [Tapo] Trying to login again.
[5/29/2022, 7:28:27 PM] [Tapo] Command error: deviceInfo > 9999
[5/29/2022, 7:28:27 PM] [Tapo] Failed to get info about: [192.168.5.213](https://192.168.5.213/)

### Expected behavior

Should connect like normal 

### Logs

<img width="802" alt="Screenshot 2022-05-29 at 9 22 20 pm" src="https://user-images.githubusercontent.com/25825957/170892793-d8e3de51-989a-46e5-9bc9-d5b7c2ab4491.png">
<img width="800" alt="Screenshot 2022-05-29 at 9 22 44 pm" src="https://user-images.githubusercontent.com/25825957/170892794-256e94b8-bff4-4975-914f-b718a94d03b8.png">

### Plugin Config

{
            "addresses": [
                "192.168.5.213",
                "192.168.5.178",
                "192.168.5.179"
            ],
            "name": "Tapo",
            "email": "*",
            "password": "*",
            "platform": "HomebridgeTPLinkTapo"
        }

### Plugin Version

3.1.0

### Homebridge Version

1.4.1

### Node.js Version

16.5.0

### NPM Version

8.5.5

### Operating System

Debian

**Comment by RaresAil** [comment]
Hey, i will add support for each type of device from tapo, in the last update i check the device type and right now it supports only light bulb. I will add a test version with a debug mode in order to help me add the support

**Comment by Daveblanche** [comment]
> Hey, i will add support for each type of device from tapo, in the last update i check the device type and right now it supports only light bulb. I will add a test version with a debug mode in order to help me add the support

Awesome.  Thanks!

**Comment by RaresAil** [comment]
Hey @Daveblanche @CoderHoods can you run a debug version of the plugin?

Requirements: NodeJS

Clone the source code
```
git clone https://github.com/RaresAil/homebridge-tp-link-tapo.git
```

```
cd homebridge-tp-link-tapo
```

Switch to the debug version of the code
```
git checkout -b feat/support-smart-outlet
```

Install the local deps
```
npm install
```

Build the plugin and run a local hombridge
```
npm run watch
```

And from there scan the QR code and see the logs

**Comment by Daveblanche** [comment]
Hi there
I will do, but am away from home for a couple weeks…and need to get my head around your instructions when I am on the Homebridge server: Mac OS.

**Comment by RaresAil** [comment]
@Daveblanche I bought a P100 and tested it with the new changes and is working, i will do some more testing (i want to see if i get info about if the socket is used by some device to display it in the app)

**Comment by Daveblanche** [comment]
I have a couple of P110 also, so can test those, when I get home

**Comment by RaresAil** [comment]
I released the version 3.2.0 which brings the support for plugs, just update and let me know if it works 😄

**Comment by RaresAil** [comment]
I am not sure which is the diff between 100 and 110 but should work the same

Edit: what i found on internet is that P110 is the UK model

**Comment by Daveblanche** [comment]
Hi there, Sorry to open this up again.
I i stalled the update over vpn to my house. The plug-in now shows the plugs as sockets AND lights. My wife hated me, so I reverted to the older release.

**Comment by RaresAil** [comment]
Hey, and the issue is that is shows them as sockets? From the accessory settings on home app, you cand display the outlet as a light


![image](https://user-images.githubusercontent.com/47503490/172229377-ef106da3-6c18-49cb-b2cd-04c5cd0191c6.png)

Under the room name

**Comment by Daveblanche** [comment]
Hi
It shows both, side by side. The switch doesn’t do anything on our setup at home, and just the slider works for the “bulb” which is the socket...

**Comment by RaresAil** [comment]
Try to clear from the config all the ips for all devices, restart to clear all the current devices, then add them back and restart, then should be correct

**Comment by Daveblanche** [comment]
> Try to clear from the config all the ips for all devices, restart to clear all the current devices, then add them back and restart, then should be correct

And it works perfectly!
