### ISSUE TITLE
Can I get help with this error?

### ISSUE THREAD

**Issue by lukeytm** [RaresAil/homebridge-tplink-smart-light#16]
### Describe The Bug

The lights worked to begin with, now I get this error. It even causes the Homebridge UI to not be accessible sometimes. 

### Expected behavior

Not this. To be able to access the one tapo light.

### Logs

20/06/2022, 23:00:11] [TPLink Tapo Platform] Error sending command: deviceInfo AxiosError: connect EHOSTUNREACH 192.168.1.42:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  port: 80,
  address: '192.168.1.42',
  syscall: 'connect',
  code: 'EHOSTUNREACH',
  errno: -113,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 352
    },
    method: 'post',
    url: 'http://192.168.1.42/app',
    data: '{"method":"handshake","params":{"key":""},"requestTimeMils":1655762408063}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/app',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.1.42',
      port: null,
      nativeProtocols: [Object],
      pathname: '/app'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 352,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /app HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Content-Length: 352\r\n' +
        'Host: 192.168.1.42\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/app',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.1.42',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.1.42/app',
    [Symbol(kCapture)]: false
  }
}
[20/06/2022, 23:00:11] [TPLink Tapo Platform] Failed to get info about: 192.168.1.42 | The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
[20/06/2022, 23:00:11] [TPLink Tapo Platform] Retry to connect in 10s : 192.168.1.42
[20/06/2022, 23:00:11] [Govee] ✓ Setup complete. Want to see this plugin in your own language? Let me know!
[20/06/2022, 23:00:21] [TPLink Tapo Platform] Try for 192.168.1.42 : 19/20
[20/06/2022, 23:00:24] [TPLink Tapo Platform] Error sending command: deviceInfo AxiosError: connect EHOSTUNREACH 192.168.1.42:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  port: 80,
  address: '192.168.1.42',
  syscall: 'connect',
  code: 'EHOSTUNREACH',
  errno: -113,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function] },
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.27.2',
      'Content-Length': 352
    },
    method: 'post',
    url: 'http://192.168.1.42/app',
    data: '{"method":"handshake","params":{"key":"-----BEGIN PUBLIC KEY-----\\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFrhWvP1TAg5utz8lCSUrul7IE\\n4le7+GgZTKx13WULiT5g78P+/e2wTpwkZcuch83jVhJnDYHHXAo5SqtvdKr+HIoG\\nUdGZo9s7V/gawzYEwFt6jG8o/vC6INieZ0DcCGgaRHshPinkzWZoYngc43SAzDNV\\nW4llPNvSKxujUs5yzQIDAQAB\\n-----END PUBLIC KEY-----\\n"},"requestTimeMils":1655762421692}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/app',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.1.42',
      port: null,
      nativeProtocols: [Object],
      pathname: '/app'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 352,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /app HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.27.2\r\n' +
        'Content-Length: 352\r\n' +
        'Host: 192.168.1.42\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/app',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.1.42',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.1.42/app',
    [Symbol(kCapture)]: false
  }
}
[20/06/2022, 23:00:24] [TPLink Tapo Platform] Failed to get info about: 192.168.1

### Plugin Config

{
    "addresses": [
        "192.168.1.42"
    ],
    "name": "TPLink Tapo Platform",
    "email": "lXXXXXX.com",
    "password": "XXXXXX",
    "platform": "HomebridgeTPLinkTapo"
}

### Plugin Version

v3.2.0

### Homebridge Version

v1.4.1

### Node.js Version

v16.15.0

### NPM Version

Unsure, sorry

### Operating System

Raspbian GNU/Linux Bullseye (11)

**Comment by RaresAil** [comment]
Hello, that error means that the light bulb wasn't powered up or it wasn't connected to your router, also to not block homebridge, setup all the plugins as child bridges

**Comment by lukeytm** [comment]
Hi, the bulb is connected and accessible through the Tapo app.

It was previously accessible via HomeKit and homebridge too. Nothing has
changed to now make this unaccessible.

What else can I do to diagnose?

**Comment by RaresAil** [comment]
Maybe the IP address has changed, check it again, if it changed, configure your router to have a static one for that device

**Comment by lukeytm** [comment]
Nope! Checked it. The IP address of the device state the same. Really odd...

**Comment by lukeytm** [comment]
Yep checked the IP is correct and reserved. Still nothing, any ideas?

**Comment by lukeytm** [comment]
Error:

[21/06/2022, 21:04:11] [TPLink Tapo Platform] Command error: deviceInfo >
9999
[21/06/2022, 21:04:11] [TPLink Tapo Platform] Failed to get info about:
192.168.1.42

**Comment by RaresAil** [comment]
If you ping the bulb from the server? **ping 19.168.1.42**

**Comment by RaresAil** [comment]
**Closed for inactivity**

**Comment by lukeytm** [comment]
Hi can we reopen this kindly?

Still same issues, new router and internet connection. All other plugins working fine.

The IP for this particular thing is 192.168.1.178

What do you mean by ping? If insert in my browser, it simply responds '200 OK'

Best,
Luke Taplin-McCallum
