### ISSUE TITLE
TP Link Kasa Smart Light Switch HS200P3

### ISSUE THREAD

**Issue by hughvia** [RaresAil/homebridge-tplink-smart-light#18]
### Describe The Bug

No Bug. Wanted to know if the TP Link Kasa Smart Light Switch HS200P3 could be added to Homebridge,

Thank You

### Expected behavior

-

### Logs

-

### Plugin Config

-

### Plugin Version

-

### Homebridge Version

1.5.0

### Node.js Version

-

### NPM Version

-

### Operating System

Apple OS High Sierra

**Comment by RaresAil** [comment]
Can you run the plugin and post the logs, if the device is not supported it will show an error and i need the information from that error to can add support for it

**Comment by RaresAil** [comment]
I checked, Tapo and Kasa are not compatible and i will not add support for it as this plugin is Tapo specific
