### ISSUE TITLE
Homekit Adaptive Lighting not working

### ISSUE THREAD

**Issue by joshpine** [RaresAil/homebridge-tplink-smart-light#19]
### Describe The Bug

When using the homekit adaptive lighting setting, homebridge throws the error: "[TPLink Tapo] Command error: colorTemp > -1008". I'm using the Tapo L900-5 light strip.

### Expected behavior

Colour temperature of strip should change throughout the day according to ambient light temperature.

### Logs

[25/07/2022, 15:32:22] [TPLink Tapo] Command error: colorTemp > -1008

### Plugin Config

{
            "addresses": [
                "192.168.x.xx"
            ],
            "name": "TPLink Tapo",
            "email": "example@gmail.com",
            "password": "example_password",
            "platform": "HomebridgeTPLinkTapo",
            "_bridge": {
                "username": "bridge_username",
                "port": bridge_port
            }
        }

### Plugin Version

v3.2.0

### Homebridge Version

v1.5.0

### Node.js Version

v16.16.0

### NPM Version

v8.11.0

### Operating System

Debian GNU/Linux Buster (10)

**Comment by RaresAil** [comment]
I managed to replicate the issue, i will work on it

**Comment by RaresAil** [comment]
In version 3.2.1 will fix the issue, the led strip does not support color temperature and i blocked it
