### ISSUE TITLE
Multiple TAPO sockets not possible

### ISSUE THREAD

**Issue by DobrakAG** [RaresAil/homebridge-tplink-smart-light#22]
### Describe The Bug

When I add another TAPO socket IP, plugin is not adding it. 

### Expected behavior

add second socket.

### Logs

[31/08/2022, 12:09:40] [Tapo] Failed to get info about: 192.168.x.xx6 | Accessories must be created with a non-empty displayName.
[31/08/2022, 12:09:40] [Tapo] Retry to connect in 10s : 192.168.x.xx6
[31/08/2022, 12:09:50] [Tapo] Try for 192.168.2.226 : 1/20

### Plugin Config

{
            "addresses": [
                "192.168.x.xx5",
                "192.168.x.xx6"
            ],
            "name": "Tapo",
            "email": "xx@xxx.xx",
            "password": "xxxx",
            "_bridge": {
                "username": "xx:xx:xx:xx:xx:xx",
                "port": 44789
            },
            "platform": "HomebridgeTPLinkTapo"
        }

### Plugin Version

v3.2.1

### Homebridge Version

v3.2.1

### Node.js Version

v16.16.0

### NPM Version

8.11.0

### Operating System

Debian GNU/Linux 11 (bullseye)

**Comment by RaresAil** [comment]
Hello, how are the sockets named in tapo app?

**Comment by RaresAil** [comment]
Are there more logs?

**Comment by DobrakAG** [comment]
Hello, the second (new) socked had default name. Once I read your message I change the name to "something" and it start working! 
Thank you for the hint!

**Comment by RaresAil** [comment]
> Hello, the second (new) socked had default name. Once I read your message I change the name to "something" and it start working!
> Thank you for the hint!

Hey, glad it works 😄
