### ISSUE TITLE
 [TPLink Tapo Platform] Command error: deviceInfo > 9999

### ISSUE THREAD

**Issue by lukeytm** [RaresAil/homebridge-tplink-smart-light#23]
### Describe The Bug

It won't connect to the lights.
* I've ensured the IP is correct and doesn't change
* It's set up as a child bridge
* If I enter http://192.168.1.162 in my browser, it returns 200-OK

### Expected behavior

Lights to work

### Logs

[02/10/2022, 15:59:51] [TPLink Tapo Platform] Try for 192.168.1.162 : 19/20
[02/10/2022, 15:59:52] [TPLink Tapo Platform] Session expired
[02/10/2022, 15:59:52] [TPLink Tapo Platform] Trying to login again.
[02/10/2022, 15:59:52] [TPLink Tapo Platform] Command error: deviceInfo > 9999
[02/10/2022, 15:59:52] [TPLink Tapo Platform] Failed to get info about: 192.168.1.162
[02/10/2022, 15:59:52] [TPLink Tapo Platform] Retry to connect in 10s : 192.168.1.162

### Plugin Config

{
    "bridge": {
        "name": "Homebridge 3B13",
        "username": "0E:95:4A:55:BB:22",
        "port": 51869,
        "pin": "947-65-125",
        "advertiser": "ciao",
        "bind": [
            "wlan0"
        ]
    },
    "accessories": [
        {
            "name": "Dummy Switch",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch",
            "_bridge": {
                "username": "0E:AA:14:59:54:B6",
                "port": 41027
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Govee",
            "username": "luxe",
            "password": "Tx",
            "apiKey": "02a0e174-aa9c-407d-a1b8-730e4f560f21",
            "platform": "Govee",
            "_bridge": {
                "username": "0E:14:4A:3E:AD:17",
                "port": 54597
            }
        },
        {
            "name": "WizSmarthome",
            "enableScenes": false,
            "platform": "WizSmarthome",
            "_bridge": {
                "username": "0x:D9",
                "port": x30
            }
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome",
            "_bridge": {
                "username": "x:93",
                "port": 40x
            }
        },
        {
            "addresses": [
                "192.168.1.162"
            ],
            "name": "TPLink Tapo Platform",
            "email": "lukexom",
            "password": "xxx",
            "platform": "HomebridgeTPLinkTapo",
            "_bridge": {
                "username": "0E:6C:C8:C3:38:2C",
                "port": 34290
            }
        }
    ],
    "disabledPlugins": []
}

### Plugin Version

homebridge-tp-link-tapo v3.2.1

### Homebridge Version

v1.5.0

### Node.js Version

v16.15.0

### NPM Version

Not sure what this is

### Operating System

Mac OS (plug-in is installed on RPi)

**Comment by RaresAil** [comment]
Hey @lukeytm did you changed your tapo account password?

**Comment by lukeytm** [comment]
No I didn’t!

Best,
Luke Taplin-McCallum

**Comment by RaresAil** [comment]
Try to remove them fron the account and repair them

**Comment by lukeytm** [comment]
Hi, I've done that - the IP generated is still the same:

[13/10/2022, 09:45:41] [TPLink Tapo Platform] Try for 192.168.1.162 : 19/20

[13/10/2022, 09:45:42] [TPLink Tapo Platform] Session expired

[13/10/2022, 09:45:42] [TPLink Tapo Platform] Trying to login again.

[13/10/2022, 09:45:43] [TPLink Tapo Platform] Command error: deviceInfo > 9999

[13/10/2022, 09:45:43] [TPLink Tapo Platform] Failed to get info about: 192.168.1.162

[13/10/2022, 09:45:43] [TPLink Tapo Platform] Retry to connect in 10s : 192.168.1.162

Best,
Luke Taplin-McCallum

**Comment by lukeytm** [comment]
Could it be because my homebridge RPi is on 5ghz and Tapo on 2.4ghz? (The router does the splitting automatically)

Best,
Luke Taplin-McCallum

**Comment by anthea-w** [comment]
Hi, I thought I was having the same problem. 
I was using the IP address I got for the bulb from its own WiFi network. However, after I added the bulb to the Tapo app and looked at its' settings, the IP address had changed. 
Here is my config for this plugin, I hope this is helpful.
`{
            "platform": "HomebridgeTPLinkTapo",
            "name": "TPLink Tapo Platform",
            "email": "redacted",
            "password": "redacted",
            "addresses": [
                "192.168.1.70"
            ],
            "_bridge": {
                "username": "0E:4F:59:A6:26:67",
                "port": 46090
            }
        }`

**Comment by lukeytm** [comment]
Hi, I've tried ensuring all devices are on 2.4Ghz. Also, the IP address within the Tapo app and within the router admin console, are the same. Still not sure what to do

Best,
Luke Taplin-McCallum

**Comment by RaresAil** [comment]
Hmm, what you could try is to un pair them, delete the account and create a new one and repair them, there was a similar issue and this helped, if this is not working, i don't know how to help you. Also what model is it?

**Comment by lukeytm** [comment]
I've fixed it! I did a reset on my account to a new password. How very ODD! Thanks

Best,
Luke Taplin-McCallum

**Comment by RaresAil** [comment]
Indeed is very weird how tapo works, glad is working now

**Comment by VrtlBrown** [comment]
I’m having this exact problem but resetting the password isn’t helping. Any ideas on what else I can try?

Recreating my account would be very drastic as it’s linked to my TP Link account where I have lots of devices working well.

**Comment by RaresAil** [comment]
> I’m having this exact problem but resetting the password isn’t helping. Any ideas on what else I can try?
> 
> 
> 
> Recreating my account would be very drastic as it’s linked to my TP Link account where I have lots of devices working well.

Hey, I don't know any other fix for that
