### ISSUE TITLE
Can you support the TRV device type?

### ISSUE THREAD

**Issue by Jimbwlah** [RaresAil/homebridge-tplink-smart-light#30]
### Describe The Bug

Hi,

I’ve been using your plugin recently and it’s worked flawlessly. I’ve ordered some of the new KE100 Thermostatic Radiator Valves (https://www.tp-link.com/uk/home-networking/smart-thermostat/ke100/) and I was wondering if you could implement a new device type to support these please?

Thanks

### Expected behavior

KE100 is discovered as a supported device type

### Logs

N/A

### Plugin Config

N/A

### Plugin Version

N/A

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

N/A

**Comment by RaresAil** [comment]
I will take a look

**Comment by RaresAil** [comment]
Kasa is on a different API than regular Tapo devices, this plugin is not compatible with Kasa
