### ISSUE TITLE
Device Request

### ISSUE THREAD

**Issue by the1maximus** [RaresAil/homebridge-tplink-smart-light#32]
### Describe The Bug

Looking to see if you can add the new Tapo - RV10 Lite (Robot Vacuum).

### Expected behavior

n/a

### Logs

na

### Plugin Config

na

### Plugin Version

3.2.2

### Homebridge Version

4.50.2

### Node.js Version

16.18.0

### NPM Version

1.6.0

### Operating System

Docker

**Comment by RaresAil** [comment]
I need the device in order to can add support for it and it is a complex implementation

**Comment by DaveGut** [comment]
Some data.  I have successfully integrated the robovac (RV10) into HUBITAT ENVIRONMENT.  Does not help here except I developed protocol and command data as part of my errort.  Location:  https://github.com/DaveGut/TAPO-Robovac-Dev
