### ISSUE TITLE
Device Request:  (SMART.TAPOSWITCH)

### ISSUE THREAD

**Issue by steveredden** [RaresAil/homebridge-tplink-smart-light#34]
### Describe The Bug

S505D Dimmer Switch (single pole) fails to load

### Expected behavior

S505D Dimmer Switch is exposed.

### Logs

[3/26/2023, 8:46:55 AM] [Tapo] Adding new accessory: Smart Switch
[3/26/2023, 8:46:55 AM] [Tapo] Failed to register accessory "Smart Switch" of type "Unknown" (SMART.TAPOSWITCH)

### Plugin Config

{
            "addresses": [
                "192.168.1.33"
            ],
            "name": "Tapo",
            "email": "",
            "password": "",
            "platform": "HomebridgeTPLinkTapo"
        }

### Plugin Version

3.2.2

### Homebridge Version

1.6.0

### Node.js Version

18.12.1

### NPM Version

x

### Operating System

Ubuntu Focal Fossa (20.04.5 LTS)

**Comment by RaresAil** [comment]
I need the device to be able to support it, and don't have it
