### ISSUE TITLE
P110 Current/Power Measurement

### ISSUE THREAD

**Issue by Ben19851337** [RaresAil/homebridge-tplink-smart-light#37]
### Describe The Bug

P110 is capable of Current/Power Measurement. Very Nice to have the measurements exposed to HomeKit for using Information in e.g. EVE App. :)

### Expected behavior

P110 should expose measurements to HomeKit

### Logs

...

### Plugin Config

...

### Plugin Version

...

### Homebridge Version

...

### Node.js Version

...

### NPM Version

...

### Operating System

...

**Comment by RaresAil** [comment]
Tried in the past and it was not possible, I might check it again in the future

**Comment by Ben19851337** [comment]
This alternative PlugIn can do it. I like your PlugIn more. So I would like if you can integrate :)

https://github.com/apatsufas/homebridge-tapo-p100#readme

**Comment by RaresAil** [comment]
I will check it and if it possible it will go in the next release
