### ISSUE TITLE
Add Support for home hub (H100) and connected devices

### ISSUE THREAD

**Issue by WollfWizard** [RaresAil/homebridge-tplink-smart-light#38]
### Describe The Bug

This plugin is a life saver and really help me link everything in my home together! The one thing that’s missing though is the ability to add Home Hubs like the H100 and devices that can only connect to it i.e. the T110 (door sensor). This will really help integrate and advance automations with these linked products! Thanks guys

### Expected behavior

The hub will provide access to additional Tapo devices and allow automations such as lights durning on when the door sensor opens

### Logs

Feature request - no logs

### Plugin Config

"name": "TP-Link Tapo",
            "email": "xxx@xxx.xxx",
            "password": "Password",
            "_bridge": {
                "username": "00:00:00:00:00:00",
                "port": 51005
            },
            "platform": "HomebridgeTPLinkTapo"

### Plugin Version

3.2.2

### Homebridge Version

1.6.0

### Node.js Version

16.16.0

### NPM Version

8.11.0

### Operating System

MacOS

**Comment by RaresAil** [comment]
I can't integrate home hubs as this plugin integrates each accessory individually
