### ISSUE TITLE
Device Request: Tapo P300

### ISSUE THREAD

**Issue by Lohengrin99** [RaresAil/homebridge-tplink-smart-light#40]
### Describe The Bug

Adding the IP address of the device leads to an error msg: "Failed to get info about: 192.168.1.182 | Accessories must be created with a non-empty displayName."

Tapo P300 is in network with IP address ...182

### Expected behavior

That it works like the P115

### Logs

[5/19/2023, 2:45:24 AM] [TPLink Tapo Platform] Retry to connect in 10s : 192.168.1.182
[5/19/2023, 2:45:34 AM] [TPLink Tapo Platform] Try for 192.168.1.182 : 1/20
[5/19/2023, 2:45:35 AM] [TPLink Tapo Platform] Adding new accessory: 
[5/19/2023, 2:45:35 AM] [TPLink Tapo Platform] Failed to get info about: 192.168.1.182 | Accessories must be created with a non-empty displayName.
[5/19/2023, 2:45:35 AM] [TPLink Tapo Platform] Retry timeout: 192.168.1.182

### Plugin Config

       {
            "name": "TPLink Tapo Platform",
            "email": "xxx",
            "password": "xxx",
            "platform": "HomebridgeTPLinkTapo",
            "addresses": [
                "192.168.1.181",
                "192.168.1.182"
            ]
        }

### Plugin Version

3.2.2

### Homebridge Version

1.6.1

### Node.js Version

Synology 18.12.0

### NPM Version

8.19.2

### Operating System

DSM 7

**Comment by RaresAil** [comment]
Go in the tapo app and rename the device there

**Comment by Lohengrin99** [comment]
Well, the P300 is actually three devices in one, and under one IP address, as is't a 3-socket board, and I renamed all three sockets since it's in the network, but I can only switch any socket via the Tapo app, but not in Home or through HomeBridge. This works (for now) well with the P115 socket (single), so I'd desire to have that funcional for the P300 as well

**Comment by RaresAil** [comment]
@Lohengrin99 Sadly I don't have the device so i can add support for it

**Comment by RaresAil** [comment]
@Lohengrin99 I seen that P300 has HomeKit support
