### ISSUE TITLE
P110 Contact Sensor when in use

### ISSUE THREAD

**Issue by danieljbnz** [RaresAil/homebridge-tplink-smart-light#43]
### Describe The Bug

Is it possible to add a contact sensor to devices that can report energy usage (specifically the P110) that shows when the device is in use. A setting could be enabled that if the current usage is greater than x watts open the contact sensor and when it is less than x watts close the contact sensor. 

The x watts could be user configurable. This will enable to see what is currently using power. 

### Expected behavior

When the P110 is in use the contact sensor is open, when it is not in use the contact sensor is closed. 

### Logs

n/a

### Plugin Config

n/a

### Plugin Version

n/a

### Homebridge Version

n/a

### Node.js Version

n/a

### NPM Version

n/a

### Operating System

n/a

**Comment by RaresAil** [comment]
I will check on it in July

**Comment by RaresAil** [comment]
I got more information, this feature will be implemented in the next version which will be released in few days @danieljbnz

**Comment by RaresAil** [comment]
Done in 3.4.0
