### ISSUE TITLE
Tapo T310 Support

### ISSUE THREAD

**Issue by parryg** [RaresAil/homebridge-tplink-smart-light#44]
### Describe The Bug

Is it possible to add support for the Tapo T310 temperature & humidity sensor?

### Expected behavior

Display info from the sensor.

### Logs

N/A

### Plugin Config

N/A

### Plugin Version

N/A

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

N/A

**Comment by RaresAil** [comment]
Hello @parryg i don't have the device so i can't add support for it
