### ISSUE TITLE
Read Handler was slow to respond & event emitter leak

### ISSUE THREAD

**Issue by thespurofthings** [RaresAil/homebridge-tplink-smart-light#45]
### Describe The Bug

I get a warning about this plugin slowing down Homebridge (which is not the issue!), it's now added in "The read handler for the characteristic 'XXX' was slow to respond!" 

Additionally, I now get this alternating between "end listeners added" and "disconnect listeners added": MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

### Expected behavior

Unsure!

### Logs

> Deleted for privacy

### Plugin Config

{
  "_bridge" : {
    "port" : 45050,
    "username" : "0E:5D:C0:83:66:26"
  },
  "addresses" : [
    "192.168.0.XXX",
    "192.168.0.XXX",
    "192.168.0.XXX",
    "192.168.0.XXX",
    "192.168.0.XXX",
    "192.168.0.XXX",
    "192.168.0.XXX"
  ],
  "email" : "XXXXX",
  "name" : "Tapo Devices",
  "password" : "XXXXX",
  "platform" : "HomebridgeTPLinkTapo"
}

### Plugin Version

3.2.2

### Homebridge Version

1.6.1

### Node.js Version

16.16.0

### NPM Version

3.2.2

### Operating System

macOS Ventura

**Comment by RaresAil** [comment]
Hey, do the light bulb turns off often?

**Comment by thespurofthings** [comment]
Hey mate! 

They don’t turn off by themselves, only two of my lights are randomly
affected. however, the Home app will show them on when they aren’t, and
vice versa. Tapping them to switch them on and off doesn’t work 100% of
the time with only 2 lights - I’ve reset them all and added them back
into Homebridge with updated IP addresses - same thing! Very odd. 

It hasn’t been always like this I’ve noted it’s appeared in the last six
weeks or so. 

On July 2, 2023, Nicolae-Rares Ailincai ***@***.***>
wrote:
> Hey, do the light bulb turns off often?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/RaresAil/homebridge-tp-link-
tapo/issues/45#issuecomment-1616377697>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BA2S3SXPRHDZ27KCVBNSYZTXOEALJANCNFSM6AAAAAAZ3DSFWQ>.
You are receiving this because you authored the thread.Message ID:
***@***.***>


--
Sent with HEY <https://hey.com/sent>

**Comment by RaresAil** [comment]
From the logs it looks like the Light Bulbs are not responding @thespurofthings , that is why i asked if they are turning off like a power loss, what you could try is to remove 1 by 1 from config and see with how many light bulbs you can use the plugin

**Comment by thespurofthings** [comment]
Sure will try this and respond this weekend! 

They seem to be more stable now in the last week. The "not responding"
is if theyve been switched off at the light switch, which some guests do
when they come over, I'll see how they go in the next few days as its
just me at home

On July 6, 2023, Nicolae-Rares Ailincai ***@***.***>
wrote:
> From the logs it looks like the Light Bulbs are not responding
> @thespurofthings <https://github.com/thespurofthings> , that is why i
> asked if they are turning off like a power loss, what you could try is
> to remove 1 by 1 from config and see with how many light bulbs you can
> use the plugin
>

—
Reply to this email directly, view it on GitHub
<https://github.com/RaresAil/homebridge-tp-link-
tapo/issues/45#issuecomment-1623067509>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/BA2S3SXQIT64BDKYLUYEF7LXOZLKHANCNFSM6AAAAAAZ3DSFWQ>.
You are receiving this because you were mentioned.Message ID:
***@***.***>


--
Sent with HEY <https://hey.com/sent>

**Comment by RaresAil** [comment]
Any updates? @thespurofthings

**Comment by thespurofthings** [comment]
So the tapo lights I have are on their own child bridge. I have been unable to reproduce it until today when I rebooted the macmini I use as a homebridgee. it tries 20 times per light, to login, but then gives session expired, THEN it says memory leak detected. I am not sure whats going but listeners being 'added' is no longer showing, but the Homebridge UI and Tapo Plugin slow it all down, umsire what that is! 

Below is the last attempts at Homebridge to run the login:

[0;36mLoading logs using native method...
[0m[0;36mFile: /Users/thespurofthings/.homebridge/homebridge.log

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m Try for 192.168.0.241 : 1/20

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m Session expired

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m Trying to login again.

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m [31mCommand error: deviceInfo > 9999[39m

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m [31mFailed to get info about: 192.168.0.241[39m

[37m[7/31/2023, 5:57:44 PM] [39m[36m[Tapo Devices][39m Retry timeout: 192.168.0.241

(node:1376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

(Use `node --trace-warnings ...` to show where the warning was created)

(node:1376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

(node:1376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

(node:1376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 childBridgeStatusUpdate listeners added to [HomebridgeIpcService]. Use emitter.setMaxListeners() to increase limit

(node:1376) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

**Comment by RaresAil** [comment]
Update the homebridge and node version to 18, that might fix the issue, i can't reproduce it on node 18
