### ISSUE TITLE
Tapo T310

### ISSUE THREAD

**Issue by Ubuquie** [RaresAil/homebridge-tplink-smart-light#46]
### Describe The Bug

Please develop support for the T310 Temperature and Humidity Sensor.  The sensor works via a hub in my case the Tapo H100 Smart Hub with chime.

### Expected behavior

N/A

### Logs

N/A

### Plugin Config

N/A

### Plugin Version

N/A

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

OSX

**Comment by RaresAil** [comment]
Hey @Ubuquie i can't because i don't have the device

**Comment by Ubuquie** [comment]
Thanks, @RaresAil, no problem.  I would like to learn how to develop this code, but not sure where to start. Are there 'how to' guides or instructions you can refer me to please?

**Comment by Ubuquie** [comment]
Hi, @RaresAil, actually, I found Node School, I will start there.  Cheers

**Comment by RaresAil** [comment]
Nice, well good luck!
