### ISSUE TITLE
Tapo T110 Support

### ISSUE THREAD

**Issue by lamnian** [RaresAil/homebridge-tplink-smart-light#48]
### Describe The Bug

Is it possible to add support for the TTapo T110 contact sensor?

### Expected behavior

-

### Logs

-

### Plugin Config

-

### Plugin Version

-

### Homebridge Version

-

### Node.js Version

-

### NPM Version

-

### Operating System

-

**Comment by RaresAil** [comment]
Hello, i don't have the device and because of that i can't add support for it

**Comment by lamnian** [comment]
Can I help in someway, since ai have the device?Thank You,Constantine Katevas+306945550900On 31 Aug 2023, at 4:56 PM, Nicolae-Rares Ailincai ***@***.***> wrote:﻿
Hello, i don't have the device and because of that i can't add support for it

**Comment by RaresAil** [comment]
Hey @lamnian i got news, the T110 will be added in version 3.3.0

**Comment by lamnian** [comment]
Awesome, thanks for the update!

**Comment by DeanKamitsis** [comment]
[10/09/2023, 18:22:44] [homebridge-tp-link-tapo] This plugin generated a warning from the characteristic 'Status Low Battery': characteristic value expected valid finite number and received "undefined" (undefined). See https://homebridge.io/w/JtMGR for more info.

**Comment by RaresAil** [comment]
I will look into it
