### ISSUE TITLE
No Support for Tapo Cameras

### ISSUE THREAD

**Issue by gebjeff** [RaresAil/homebridge-tplink-smart-light#50]
### Describe The Bug

I just purchased a Tapo C420 camera and an H200 hub. I've entered my TP-Link account name and password in the plugin and the plugin generates the following log errors

### Expected behavior

The plugin will work with my camera.

### Logs

[homebridge.log.txt](https://github.com/RaresAil/homebridge-tp-link-tapo/files/12467715/homebridge.log.txt)

### Plugin Config

{
            "addresses": [
                "192.168.1.32"
            ],
            "name": "xxx",
            "email": "xxx@xxx.com",
            "password": "xxx",
            "platform": "HomebridgeTPLinkTapo"

### Plugin Version

homebridge-tp-link-tapo v3.2.2

### Homebridge Version

te v1.6.1

### Node.js Version

v18.17.1

### NPM Version

 v18.17.1

### Operating System

Debian GNU/Linux 11 (bullseye)

**Comment by RaresAil** [comment]
Hello, the camera is not supported and I don't have the means to add support for it at this time, the hub will get a support soon with the tapo button

**Comment by gebjeff** [comment]
Thanks for the quick response. Can you elaborate on what you mean regarding the tapo button? TIA.

**Comment by RaresAil** [comment]
The devices H100 and S200 will be added to the plugin

**Comment by gebjeff** [comment]
Thank you for this info. Looking forward to it.Regards, Jeff Edelheit12518 Chasbarb TerraceOak Hill, VA 20171-2468(703) 758-0241 (h)(703) 626-4605 (c)On Aug 31, 2023, at 7:02 AM, Nicolae-Rares Ailincai ***@***.***> wrote:﻿
The devices H100 and S200 will be added to the plugin

**Comment by RaresAil** [comment]
As i don't have the device, i can't add support for it
