### ISSUE TITLE
Tapo Switches (eg: S500D) are unsupported

### ISSUE THREAD

**Issue by raajiivv** [RaresAil/homebridge-tplink-smart-light#53]
### Describe The Bug

Tapo switches are currently unsupported. 
Homebridge shows an error log 
`[9/4/2023, 7:24:24 PM] [TPLink Tapo Platform] Failed to register accessory "Bedroom light" of type "Unknown" (SMART.TAPOSWITCH)`

### Expected behavior

Please add support to Tapo switches. Thanks!

### Logs
```
[9/4/2023, 7:24:23 PM] [TPLink Tapo Platform] Launched child bridge with PID 9846
[9/4/2023, 7:24:23 PM] Registering platform 'homebridge-tp-link-tapo.HomebridgeTPLinkTapo'
[9/4/2023, 7:24:23 PM] [TPLink Tapo Platform] Loaded homebridge-tp-link-tapo v3.3.0 child bridge successfully
[9/4/2023, 7:24:23 PM] Homebridge v1.6.1 (HAP v0.11.1) (TPLink Tapo Platform) is running on port 46874.
[9/4/2023, 7:24:24 PM] [TPLink Tapo Platform] Adding new accessory: Bedroom light
[9/4/2023, 7:24:24 PM] [TPLink Tapo Platform] Failed to register accessory "Bedroom light" of type "Unknown" (SMART.TAPOSWITCH)
```

### Plugin Config

```
{
    "addresses": [
        "192.168.1.115"
    ],
    "name": "TPLink Tapo Platform",
    "email": "xxxx",
    "password": "xxxx",
    "_bridge": {
        "username": "0E:98:57:A7:35:B4",
        "port": 46874
    },
    "platform": "HomebridgeTPLinkTapo"
}
```

### Plugin Version

v3.3.0

### Homebridge Version

v1.6.1

### Node.js Version

v18.16.0

### NPM Version

v9.5.1

### Operating System

ubuntu

**Comment by RaresAil** [comment]
Hey, can you provide a ss from the tapo app? I want to see if it has logs

**Comment by raajiivv** [comment]
Attaching a ss of the device info. Let me know if you wanted something else.
![IMG_2700](https://github.com/RaresAil/homebridge-tp-link-tapo/assets/5288931/96f38647-59e0-4435-9f4e-9fe28fa4917b)

**Comment by RaresAil** [comment]
I need a SS from the part where it shows the logs if is on/off

**Comment by spybroth0j** [comment]
Could you also please add support for TP Link Tapo Matter switches S505 and S505D. I have the S505 connected to a fan and HomeKit will not let me change the type from light to fan. Believe I can change the type if I add it through Homebridge. Thank you!

**Comment by RaresAil** [comment]
> Could you also please add support for TP Link Tapo Matter switches S505 and S505D. I have the S505 connected to a fan and HomeKit will not let me change the type from light to fan. Believe I can change the type if I add it through Homebridge. Thank you!

Everything that is matter should have support with homekit by default, if not you need a matter hub

**Comment by spybroth0j** [comment]
Correct, I am able to add the S505 through HomeKit directly, but can't change the controlled device to Fan from Light. This is a TP Link problem, and the work around would be to connect it via Homebridge and then change the type via Homebridge. Hope this explains. Thanks!

**Comment by S2024C** [comment]
Could you please add Tapo S505? I personally have 9 of them and 2 are fans that show light bulbs. I have emailed Tapo twice but no update so far to resolve the matter. My first email was in early November 2023. They still haven't let us change the icon from a light to a fan. We appreciate your work on this :)
