### ISSUE TITLE
request for Tapo T100 motion sensor support

### ISSUE THREAD

**Issue by dtrain01** [RaresAil/homebridge-tplink-smart-light#55]
### Describe The Bug

currently not supported

### Expected behavior

Use motion detection to activate switches

### Logs

N/A

### Plugin Config

N/A

### Plugin Version

N/a

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

N/A

**Comment by RaresAil** [comment]
Hey @dtrain01 please join on discord, i don't have the device so i will nee your help in implementing this

**Comment by josephgrovers** [comment]
Hey, I just got these devices and also noticed the T100 isn't supported just yet.
I'd of course also like to get support for the T100 motion sensor. I'm not super technical but I'd be happy to help so that people with this sensor can get going.

What can I do? I'm trying to find the Discord.

**Comment by josephgrovers** [comment]
![IMG_7534](https://github.com/RaresAil/homebridge-tp-link-tapo/assets/60372673/ebd78fc5-97f7-4086-a5e8-52fc4602760c)
![IMG_7535](https://github.com/RaresAil/homebridge-tp-link-tapo/assets/60372673/26ee7a02-a39d-4841-8a0e-a69d81b758c1)

**Comment by zindello** [comment]
I'm also after this functionality. I can give you whatever you need including remote access to my HomeBridge server if needbe. I have two motions sensors we can play with.

**Comment by jangomunkie** [comment]
I also would like support for T100 motion sensors if possible please.

**Comment by goncaloacteixeira** [comment]
Do you have an update for this? If I have time, I will try to add support for it via PR.

**Comment by Johnnyk56791234** [comment]
Hi, just wondering how do you add the t100 motion sensor to the Tapo homebridge plugin , clicked on the config in the plugin but I just see the IP add option for plugs etc - many thanks

**Comment by goncaloacteixeira** [comment]
@Johnnyk56791234 the sensor is added via an Hub, which should be in your IP list.

**Comment by Johnnyk56791234** [comment]
@goncaloacteixeira legend thanks for that update - I’ll try that now ! 🙌🏼
