### ISSUE TITLE
Unable to create automation from Tapo P110 Contact Sensor

### ISSUE THREAD

**Issue by jprabawa** [RaresAil/homebridge-tplink-smart-light#61]
### Describe The Bug

There is no option in HomeKit to create an automation based on the state of the contact sensor. When the accessory is selected for automation, only the power state on / off is available for selection. 

I think this might be fixed if the contact sensor is created as a separate accessory instead of a characteristic of the same accessory (that already has a power state)

### Expected behavior

Able to use the contact sensor state for HomeKit automations 

### Logs

-

### Plugin Config

        {
            "addresses": [
                "1.2.3.4"
            ],
            "name": "TPLink Tapo Platform",
            "email": "email@redacted.com",
            "password": "<REDACTED>",
            "platform": "HomebridgeTPLinkTapo",
            "_bridge": {
                "username": "11:22:33:44:55:66",
                "port": 12345
            }
        }

### Plugin Version

v4.0.0

### Homebridge Version

v1.6.1

### Node.js Version

v18.17.0

### NPM Version

v9.6.7

### Operating System

Raspbian GNU/Linux 11

**Comment by RaresAil** [comment]
Hey, there is possible, i do have automation when i open the door at night to turn on the lights, you need to select to create an automation when a sensors detects something

![image](https://github.com/RaresAil/homebridge-tp-link-tapo/assets/47503490/45ca83ef-3bc3-4436-9fed-e2cf1f8c75cd)

**Comment by jprabawa** [comment]
Yes, that’s the category I selected. And when I select the plug, here is the screen I get:

![IMG_9055](https://github.com/RaresAil/homebridge-tp-link-tapo/assets/1725854/e0123ca9-d2b6-4852-987b-e01cc6a04b85)

As you can see from the above, the home app won’t let me choose the contact sensor state, it only allows me to choose the power state of the plug.

**Comment by RaresAil** [comment]
I see, so you want to automate the contact sensor from the plug itself, in that case the ticket tile is wrong as you specified T110

**Comment by jprabawa** [comment]
Ah, my bad. I meant P110. I’m not sure how I can fix the title. Should I close this and file a new ticket?

**Comment by jprabawa** [comment]
Ah my bad. I’ve fixed the title. I meant to say P110

**Comment by RaresAil** [comment]
Great, i will let you know when i will start on this
