### ISSUE TITLE
Unreachable if power fails

### ISSUE THREAD

**Issue by energiumOn** [RaresAil/homebridge-tplink-smart-light#62]
### Describe The Bug

If power fails and then restores, the plugin does not reconnect automatically to the devices.
It is as if not able to reach the IP addresses of the devices and keeps trying to reconnect but without success.

### Expected behavior

The best way to address such issue is to add auto discovery using mDNS. A number of plugins on Homebridge no longer require IP addresses but mDNS. 🤗 

### Logs

[9/30/2023, 2:09:20 PM] [Tapo] Error sendin
9 command:
power AxiosError: Request faile
d with status code 403
at settle (/var/lib/homebridge/node_mo dules/homebridge-tp-link-tapo/node_modules /axios/lib/core/settle.js:19:12)
at IncomingMessage handleStreamend (/V
ar/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/adapte rs/http.js:572:11)
at
IncomingMessage.emit (node:events:5
29:35)
at endReadableNT (node:internal/stream s/readable:1368:12)
at processTicksAndRejections (node:int
ernal/process/task_queues:82:21) {
code: 'ERR_BAD REQUEST'
config: {
transitional: {
silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false
adapter: 'http'
transformRequest: [ [Function: transfo rmRequest| 1,
transiormlesponse: [ [Function: transi ormResponse] 1,
timeout:
0,
xsIfCookieName: 'XSRE-TOKEN'
xsriHeaderName:
'X-XSRE-TOKEN'
maxContentLength: -1, maxBodyLength: -1,
env: { FormData: [Function], Blob: [cl ass Blob]
validateStatus: [Function: validateSta tus],

### Plugin Config

N/A

### Plugin Version

N/A

### Homebridge Version

N/A

### Node.js Version

N/A

### NPM Version

N/A

### Operating System

N/A

**Comment by mattjc55** [comment]
I have this issue too - after power failure devices are still visibile in home app but are uncontrolable. This is new since the update that fixed the auth,

**Comment by wizardofozzie** [comment]
I'm wondering whether this is what originally [made this happen](https://github.com/RaresAil/homebridge-tp-link-tapo/issues/63)- there was a power outage.
I have never got the L610 and L630s working again

**Comment by RaresAil** [comment]
@wizardofozzie can't be as this issue about the power is fixable with a home bridge restart

**Comment by RaresAil** [comment]
@energiumOn When i will have some time i will try this

**Comment by energiumOn** [comment]
Nice… 🤗
What you’re doing is great. I totally rely on your plugin to integrate all my Tapo devices in Homekit!

**Comment by f0rkth1s** [comment]
I set up the L530B bulbs last night in my house and have the issue as described above.

The bulbs work fine when first added to the plugin, but if someone switches a bulb off at the wall and then it is powered up later on, this plug-in cannot connect to it again.

A restart of the app or container fixes the issue every time.

**Comment by energiumOn** [comment]
Yes… that’s exactly the issue. This started only to happen after the last update. I hope there would be a fix 🤗

**Comment by DmitryZemlyuk** [comment]
Hi. Still reproduced (v4.1.0), need reload child bridge with plugin for working (if you turn off the electricity and then it back on).

**Comment by sandipdsp1990** [comment]
I have a shelly switch, which I use with a smart light, and this is becoming an issue. I am using L630 bulbs. Do you have any workaround for this?

**Comment by brycepavey** [comment]
also having this issue on L530B bulbs, same error as OP

**Comment by energiumOn** [comment]
Hi man @RaresAil, any news about this issue? It started to be annoying! please have sometime to look at the issue.
Last week, I was away from home on travel and due to a power failure, the lamps were kept on for 4 days. :)
It was my fault, I did not have the Tapo app installed to show me what was happening because I relied only on the plugin!

**Comment by csytsma** [comment]
You do realize, @energiumOn, the author of this plugin doesn’t work for you, or owe you anything? He shared it to be helpful for others. I suggest you “have sometime” to fix it yourself, or pay the author to fix it, and stop being “annoying”.On Feb 18, 2024, at 3:36 AM, energiumOn ***@***.***> wrote:﻿
Hi man @RaresAil, any news about this issue? It started to be annoying! please have sometime to look at the issue.
Last week, I was away from home on travel and due to a power failure, the lamps were kept on for 4 days. :)
It was my fault, I did not have the Tapo app installed to show me what was happening because I relied only on the plugin!

**Comment by energiumOn** [comment]
@csytsma, you’re by every definition a rude person.
Teach yourself some manners SPOKESMAN…
