### ISSUE TITLE
is there support for TAPO Camera C210

### ISSUE THREAD

**Issue by cohen-sydney** [RaresAil/homebridge-tplink-smart-light#73]
### Describe The Bug

is there support for TAPO Camera C210

### Expected behavior

see the camera image in real time 

### Logs

none

### Plugin Config

none

### Plugin Version

latest

### Homebridge Version

v1.7.0

### Node.js Version

v20.9.0

### NPM Version

unsure

### Operating System

Raspian Bookworm RPI5

**Comment by RaresAil** [comment]
Hello, there is not support for cameras

**Comment by cohen-sydney** [comment]
Thanks, is the Hub H200 & TP-LINK Tapo Smart Temperature & Humidity T310 supported???
