### ISSUE TITLE
Cannot connect Tapo Smart Contact Sensor T110 managed by H200

### ISSUE THREAD

**Issue by redradoa** [RaresAil/homebridge-tplink-smart-light#93]
### Describe The Bug

First of all let me thank you and congratulate you for the work done in this Plugin
I am trying to connect to a Tapo Smart Contact Sensor T110  managed by H200
The H200 has a fixed IP (192.168.1.47) which I have used to configure the plugin
Looking at the log , it keeps trying to connect unsuccesfully
As you know, you cannot see T110 IP so I guess that it is being managed by H200. In Tapo application I can see the T110 changes of status from open to closed and viceversa without any issue at all.
Thank you very much in advance for your support
Albert

### Expected behavior

To be able to "see" the Smart Contact Sensor T110 in my homekit application

### Logs

[homebridge-tp-link-tapo.log (3).txt](https://github.com/RaresAil/homebridge-tp-link-tapo/files/15048030/homebridge-tp-link-tapo.log.3.txt)

### Plugin Config

{
    "addresses": [
        "192.168.1.47"
    ],
    "name": "redradoa",
    "email": "xxxxx@xxxx.com",
    "password": "xxxxx-xxxx-xxx",
    "platform": "HomebridgeTPLinkTapo",
    "_bridge": {
        "username": "0E:B4:D1:27:DF:3A",
        "port": 49014
    }
}

### Plugin Version

4.1.0

### Homebridge Version

20.9.0

### Node.js Version

20.9.0

### NPM Version

10.1.0

### Operating System

Mac OS Monterey 12.7.4

**Comment by RaresAil** [comment]
Tapo added support for matter even in H100, so all the hubs will no longer receive any updates

**Comment by redradoa** [comment]
Thank you for your answer. You mean that the right approach for the integration is to use Mater. Right?

**Comment by RaresAil** [comment]
Tapo released an update for the h100, I don’t have 200 to know for that as well, that natively connects to apple home, so for the hub you no longer need to use this plugin

**Comment by redradoa** [comment]
Thank you very much for your quick answer. I guess that that will also be the case with Home Assistant 
Regards
